spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/testdb
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
#        show_sql: true
        format_sql: true

  profiles:
#    include: oauth
    group:
      "local": "oauth"
      "local-real": "oauth,local-real"
      "real": "local-real,real-db,oauth"
      "real1": "real1,real-db,oauth"
      "real2": "real2,real-db,oauth"
    active: local

  session:
    store-type: jdbc
    jdbc.initialize-schema: always

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

